version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
      privy-wallet-stack:
        patterns:
          - "@privy-io/*"
          - "@reown/*"
          - "@walletconnect/*"
          - "viem"
          - "ws"
      build-and-test:
        dependency-type: "development"
    labels:
      - "dependencies"
      - "ruby-high"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
