// Generated by scripts/upload-nft-images-arweave.mjs.
// Do not edit by hand; rerun the uploader.
export const NFT_ARWEAVE_IMAGE_URIS = {
  "api/apps/ruby-high/assets/nft/cards/captain-null.png": "https://gateway.irys.xyz/FQXsSJ4gJWj9pM4Fc2RcEAcomoPSyPaRyd19ghpxVdLv",
  "api/apps/ruby-high/assets/nft/cards/eliza.png": "https://gateway.irys.xyz/G4mYFb2JgHjsCYdWLtYrhYQL1GGYUPvqaeUi4xao9cpL",
  "api/apps/ruby-high/assets/nft/cards/indra.png": "https://gateway.irys.xyz/6S94Fzxaos9mpWeRhjfaJ9ce8c6HHCSdNuBVRHie5LFy",
  "api/apps/ruby-high/assets/nft/cards/item-flashcards.png": "https://gateway.irys.xyz/H38mBQgXzZZK6vEni77FShD8Lh7vX9QVsDd6C3yL4tVQ",
  "api/apps/ruby-high/assets/nft/cards/item-hall-pass.png": "https://gateway.irys.xyz/9EsaWqjWaWKvb9a62iKr1dYSMRPGRQVaA1fpLFjWfk4q",
  "api/apps/ruby-high/assets/nft/cards/item-lab-flask.png": "https://gateway.irys.xyz/4rAuX9pMMUMfveZ9rL9yBKQD7dcPAcfgoiQzL71pr5Nr",
  "api/apps/ruby-high/assets/nft/cards/item-library-card.png": "https://gateway.irys.xyz/GW7DcPRJMum61q73hfynntUJ3zUje7yjwE7xVesLSNgU",
  "api/apps/ruby-high/assets/nft/cards/item-lunch-tray.png": "https://gateway.irys.xyz/6tvAmcFPM8cXAmxmZNciN6iYQkj5C1J84bjnFiXuoyrV",
  "api/apps/ruby-high/assets/nft/cards/item-notebook.png": "https://gateway.irys.xyz/3U8K8YGe1nEhvVjuV7ThDkLLsLZViRsAdKDKGeLV1mDS",
  "api/apps/ruby-high/assets/nft/cards/location-cafeteria.png": "https://gateway.irys.xyz/FXSukeq8KPmaZ2tBPqRMmRhruTEFSiE4mTrCThiVpCen",
  "api/apps/ruby-high/assets/nft/cards/location-courtyard.png": "https://gateway.irys.xyz/5uestScY6q33FLjFY8gfSr9k2ZDMsZzYuXLvnVCtaz6G",
  "api/apps/ruby-high/assets/nft/cards/location-greenhouse.png": "https://gateway.irys.xyz/6V6TeKMCmD6kDJHkPHeJdqcNySzXJyov7b9QtsfVw8W8",
  "api/apps/ruby-high/assets/nft/cards/location-homeroom.png": "https://gateway.irys.xyz/D4o7VmayTktEbx7HivEeWTzVvjnmbp4JrDgNzkvUwVQ",
  "api/apps/ruby-high/assets/nft/cards/location-library.png": "https://gateway.irys.xyz/44eAXJkBYuXjrV2ctE8PurKnHQ4Zg29LdzeNm1Sh5PLR",
  "api/apps/ruby-high/assets/nft/cards/location-science-lab.png": "https://gateway.irys.xyz/DDmgnZHAZ3WPqvyNVjU57ayQMY6y2WYSL7Fu1jkjbJMu",
  "api/apps/ruby-high/assets/nft/cards/lyra.png": "https://gateway.irys.xyz/7BGwmo5bhDKDhhKVcoUaKfNcaWcVU5ifHQfPqQNVyYrP",
  "api/apps/ruby-high/assets/nft/cards/mika.png": "https://gateway.irys.xyz/8AZLNaZdJDYx1jbdqFCKpS8JM12PGQD5b2U16P2pjAy5",
  "api/apps/ruby-high/assets/nft/cards/noor.png": "https://gateway.irys.xyz/3Mt6b11iNvuBHXKoqRTmDQcouwxpmzaSimWyDM6EYUAH",
  "api/apps/ruby-high/assets/nft/cards/professor-edward.png": "https://gateway.irys.xyz/63VTMvTDzdPbK8T4y1naQBwk5by43kYbpRn6wtiVyXPe",
  "api/apps/ruby-high/assets/nft/cards/rati.png": "https://gateway.irys.xyz/4gDnEdkgqayZGDQ9sSFoHuY5LSgwfuDDWmwSJR2QPbVX",
  "api/apps/ruby-high/assets/nft/cards/ravi.png": "https://gateway.irys.xyz/9gsNxRKPyeZ4AyB8Vi31VoPgxYNFapMFhkQN7TbU17AK",
  "api/apps/ruby-high/assets/nft/cards/ruby.png": "https://gateway.irys.xyz/3N7c6M2wjZa456uHysFisgmRwnV9MshJFLzgDrLY8xYB",
  "api/apps/ruby-high/assets/nft/cards/sally-science.png": "https://gateway.irys.xyz/9EEyhSHwH3k4Mm4TyAhJNSSren9ZYF7XZE8RhJ9SfGX",
  "api/apps/ruby-high/assets/nft/cards/sami.png": "https://gateway.irys.xyz/Fmhr5NjuA3ZLpWJPzRcPeAT7wfaXepxSemWBCLj4eDT3",
  "api/apps/ruby-high/assets/nft/ruby-high-card-back.png": "https://gateway.irys.xyz/8VvTzMkH7UD9xPmF8uUsEiXES8g1baidKkV4QdrNSuc6",
  "api/apps/ruby-high/assets/nft/ruby-high-first-bell-collection.png": "https://gateway.irys.xyz/CftnaUbUm6VjQn1YuuchJZZfKatZSfGFn8iKQJQAyhxf",
  "api/apps/ruby-high/assets/nft/ruby-high-pack-opened.png": "https://gateway.irys.xyz/4wkc84eGANYxfVZmoDTjK1J9dYRvUGsbhnvVcVpJHCiR",
  "api/apps/ruby-high/assets/nft/ruby-high-pack-promo.png": "https://gateway.irys.xyz/7WMBqs2dBibVw7dVCvobgNmP64KASCxcfrY3x1fL1S42",
  "api/apps/ruby-high/assets/nft/ruby-high-pack.png": "https://gateway.irys.xyz/rHyhXzuc6KNZ1dUyAYKYEVJRmbbz1xqtkRdDvey5h1p",
} as const satisfies Record<string, string>;

export function normalizeNftAssetPath(assetPath: string): string {
  const clean = assetPath.trim();
  if (!clean) return "";
  let pathname = clean;
  try {
    if (/^https?:\/\//i.test(clean)) pathname = new URL(clean).pathname;
  } catch {
    pathname = clean;
  }
  const withoutQuery = pathname.split("#", 1)[0]!.split("?", 1)[0]!;
  return withoutQuery.replace(/^\/+/, "");
}

export function nftImageUri(
  publicBaseUrl: string,
  assetPath: string,
  arweaveImageUris: Readonly<Record<string, string>> = NFT_ARWEAVE_IMAGE_URIS,
): string {
  const arweaveUri = arweaveImageUris[normalizeNftAssetPath(assetPath)]?.trim();
  if (arweaveUri) return arweaveUri;
  return `${cleanBaseUrl(publicBaseUrl)}${assetPath}`;
}

function cleanBaseUrl(value: string): string {
  return value.trim().replace(/\/+$/, "");
}
