export const DEFAULT_OPENROUTER_MODEL = "google/gemini-3.5-flash";
export const DEFAULT_STUDENT_MODEL = DEFAULT_OPENROUTER_MODEL;
export const DEFAULT_CREATOR_MODEL = DEFAULT_OPENROUTER_MODEL;
export const DEFAULT_COURSE_MODEL = "qwen/qwen3.7-max";
