export const DEFAULT_OPENROUTER_MODEL = "openai/gpt-5.6-luna";
export const DEFAULT_STUDENT_MODEL = DEFAULT_OPENROUTER_MODEL;
export const DEFAULT_CREATOR_MODEL = DEFAULT_OPENROUTER_MODEL;
export const DEFAULT_COURSE_MODEL = "openai/gpt-5.6-terra";
